version: '3.1'
services:
  pihole:
    image: pihole/pihole:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dns.rule=Host(`dns.${domain_name}`)"
        - "traefik.http.services.dns.loadbalancer.server.port=80" #uses internal docker port
        - "traefik.http.routers.dns.entrypoints=websecure"
        - "traefik.http.routers.dns.tls=true"
        - "traefik.http.routers.dns.tls.certresolver=myresolver"
        - "traefik.http.routers.dns.tls.domains[0].main=${domain_name}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8079:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: "${ADMIN_PASS}"
      PIHOLE_DNS_: "9.9.9.9;1.1.1.1"
      DNSMASQ_LISTENING: "all" #if using swarm this env variable will allow DNS to work over overlay and bridge networks.
    networks:
      - container-swarm-network
    volumes:
      - '${container_volumes_location}/pihole:/etc/pihole'
      - '${container_volumes_location}/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
networks:
  container-swarm-network:
    external: true
